# Generated by Django 3.0.2 on 2020-02-26 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 2, 26, 13, 55, 49, 96206), verbose_name='ログイン時間')),
                ('status', models.IntegerField(choices=[(1, 'in'), (0, 'out')], default=0, verbose_name='inout')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='名前')),
                ('login_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face_login.login_data')),
            ],
        ),
        migrations.AddField(
            model_name='login_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='face_login.person'),
        ),
    ]
